project:
  type: website
  output-dir: docs

  resources:
    - "Notebooks/*.png"
    - "Notebooks/*.jpg"
    - "Notebooks/*.jpeg"

website:
  title: "Bruna Taiana Almeida Brito"

  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Início

      - href: lista_disciplina.qmd
        text: Aulas

      - href: about.qmd
        text: Sobre

  page-footer:
    left: "PPEC0039 — Estatística e Planejamento de Experimentos"
    right: "Bruna Taiana Almeida Brito"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "Nesta página"
    smooth-scroll: true