project:
  type: website
  output-dir: docs

website:
  title: "Bruna Brito | Engenharia Civil"

  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Início
      - href: lista_disciplina.qmd
        text: Aulas
      - href: about.qmd
        text: Sobre

  page-footer:
    left: "PPEC0039 — Estatística e Planejamento de Experimentos"
    right: "Bruna Taiana Almeida Brito"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "Nesta página"
    smooth-scroll: true